Terraform 1
Otus-DevOps-2021-08/Sandello76_infra pull request #5
Opened 2022-01-19 22:21 UTC by Sandello76

# Выполнено ДЗ №

 - [+] Основное ДЗ
 - [+] Задание со *

## В процессе сделано:
 - настроил terraform
 - переменные вынесены в отдельный файл

## Как запустить проект:
terraform plan
terraform apply

## Как проверить работоспособность:
 - Например, перейти по ссылке http://51.250.1.85:9292/

## PR checklist
 - [+] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2022-01-19 22:23 UTC, Sandello76 commented
во время автотестов возникает ошибка 
`  ×  structure: Check repo structure (1 failed)
     ✔  File .gitignore should exist
     ×  File .gitignore content should match /\n\Z/
     expected "*.tfstate\n*.tfstate.*.backup\n*.tfstate.backup\n*.tfvars\n.terraform/*\n.idea/*\nvariables.json" to match /\n\Z/
     Diff:
     @@ -1,2 +1,8 @@
     -/\n\Z/
     +*.tfstate
     +*.tfstate.*.backup
     +*.tfstate.backup
     +*.tfvars
     +.terraform/*
     +.idea/*
     +variables.json
`
но gitignore валидный

2022-01-20 19:35 UTC, mrgreyves requested changes
Здравствуйте!)
Все верно, гитигнор валидный
Но есть нюанс - нужно добавить пустую строку в конце файла
Приключение на одну минуту
Давайте поправим =)

2022-01-20 21:54 UTC, Sandello76 commented
доброй ночи - пофиксил. странно в ide была строка  - вот что значит не привык в веб интерфейсу

2022-01-20 22:01 UTC, Sandello76 commented
> Здравствуйте!) Все верно, гитигнор валидный Но есть нюанс - нужно добавить пустую строку в конце файла Приключение на одну минуту Давайте поправим =)

доброй ночи - пофиксил. странно в ide была строка - вот что значит не привык в веб интерфейсу

2022-01-27 14:38 UTC, Sandello76 reviewed
фикс

2022-02-01 08:51 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув =)

2022-02-01 09:51 UTC, merged